### ISSUE TITLE
Mark repo as deprecated

### ISSUE THREAD

**Issue by waldyrious** [litecoin-project/old-litecoin-org#22]
It seems like this repository is deprecated in favor of https://github.com/litecoin-project/litecoin-dot-org. It would be nice to change the description field of the repository here on GitHub, which currently says simply

    Litecoin.org Project website 

...to include a deprecation notice and a link to the current repo.

Such a change can only be done in the repository settings, by repository owners or organization members. A README with this information would be nice as well, and unlike the description field, can be contributed by anyone. I can send a PR adding one if there's interest.

**Comment by losh11** [comment]
`README` clearly states ```DEPRECATED litecoin.org project website. The latest one can be found here: https://github.com/litecoin-project/litecoin.org```.

Repo description also reads `DEPRECATED`.

**Comment by waldyrious** [comment]
@losh11 that has only been the case since commit 35dd622, from 11 days ago. But good point; that commit, plus the change in the repo description, means this issue can be closed. Thanks for the heads-up :)
