### ISSUE TITLE
Big title in intro before download buttons is missing in all language except english

### ISSUE THREAD

**Issue by foufrix** [litecoin-project/old-litecoin-org#23]
There is a problem on the website just before the download button, the text is missing on all language except english.

I did not found the text in the YML file in locales enven in english.

You can see it on the picture attached

![screenshot 2017-12-28 at 10 50 57](https://user-images.githubusercontent.com/16646581/34394311-339fc926-ebbd-11e7-8ebc-8935c17e2e2b.png)
![screenshot 2017-12-28 at 10 50 43](https://user-images.githubusercontent.com/16646581/34394312-3406f286-ebbd-11e7-8a8c-645d4069157c.png)

**Comment by PeterTheOne** [comment]
this repo should be deprecated, see #22
